version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes: 
      - .:/app
    ports:
      - 8080:8080
  db:
    image: postgres:15
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: leckerlog-password
      POSTGRES_DB: leckerlog-db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080